spring:
  profiles:
    active: local
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE

logging:
  module-name: TEST
  slack:
    webhook-uri: https://hooks.slack.com/services/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
  config: classpath:logback-spring.xml